Implement allow regex in filter options (#3).
mirceanis/stfc pull request #23
Opened 2018-04-02 15:31 UTC by JDFind

2018-04-04 10:26 UTC, mirceanis requested changes

2018-04-04 10:26 UTC, mirceanis commented on src/main/groovy/ro/mirceanistor/stf/STF.groovy
> +            if (filterBySerial && !it.serial?.matches(filterBySerial as String)) {
Changing the order here makes these changes harder to follow (even though they don't appear in the order from the example)

2018-04-04 10:26 UTC, mirceanis commented on src/main/groovy/ro/mirceanistor/stf/STF.groovy
> +            if (filterByNotes && !it.notes?.matches(filterByNotes as String)) {
since devices are filtered on a "does not match" basis, the regexes used during filtering may have unintended consequences.

There needs to be a battery of tests with some example regex filters

2018-04-04 12:59 UTC, JDFind commented on src/main/groovy/ro/mirceanistor/stf/STF.groovy
> +            if (filterByNotes && !it.notes?.matches(filterByNotes as String)) {
Agreed. Will return with a test suite for this specific feature.

2018-04-04 14:12 UTC, JDFind commented on src/main/groovy/ro/mirceanistor/stf/STF.groovy
> +            if (filterByNotes && !it.notes?.matches(filterByNotes as String)) {
Done

2018-06-07 11:46 UTC, mirceanis approved these changes

2018-06-07 12:25 UTC, merged